-- Default header aliases (admin can add more; per-source overrides live in data_sources.column_mapping)
INSERT INTO field_aliases (alias_norm, canonical_field) VALUES
  ('school id','school_id'),
  ('schoolid','school_id'),
  ('sch id','school_id'),
  ('glf school id','school_id'),
  ('crm school id','school_id'),
  ('school name','school_name'),
  ('school','school_name'),
  ('institution name','school_name'),
  ('institution','school_name'),
  ('name of the school','school_name'),
  ('name of school','school_name'),
  ('school institution name','school_name'),
  ('school name with branch','school_name'),
  ('city','city'),
  ('town','city'),
  ('city town','city'),
  ('school city','city'),
  ('city name','city'),
  ('district','district'),
  ('school district','district'),
  ('district name','district'),
  ('address','address'),
  ('school address','address'),
  ('full address','address'),
  ('complete address','address'),
  ('pin code','pin_code'),
  ('pincode','pin_code'),
  ('pin','pin_code'),
  ('postal code','pin_code'),
  ('zip','pin_code'),
  ('zip code','pin_code'),
  ('school pin code','pin_code'),
  ('state','state'),
  ('school state','state'),
  ('state name','state'),
  ('board','board'),
  ('affiliation','board'),
  ('school board','board'),
  ('board of affiliation','board'),
  ('board affiliation','board'),
  ('school principal name','principal_name'),
  ('principal name','principal_name'),
  ('principal','principal_name'),
  ('name of principal','principal_name'),
  ('name of the principal','principal_name'),
  ('school principal contact','principal_contact'),
  ('principal contact','principal_contact'),
  ('principal phone','principal_contact'),
  ('principal mobile','principal_contact'),
  ('principal contact number','principal_contact'),
  ('principal phone number','principal_contact'),
  ('principal mobile number','principal_contact'),
  ('principal contact no','principal_contact'),
  ('school email','school_email'),
  ('email','school_email'),
  ('school email id','school_email'),
  ('email address','school_email'),
  ('school e mail','school_email'),
  ('school mail id','school_email'),
  ('email id','school_email'),
  ('school email address','school_email'),
  ('school coordinator name','coordinator_name'),
  ('coordinator name','coordinator_name'),
  ('coordinator','coordinator_name'),
  ('teacher coordinator name','coordinator_name'),
  ('name of coordinator','coordinator_name'),
  ('olympiad coordinator name','coordinator_name'),
  ('teacher name','coordinator_name'),
  ('school coordinator phone','coordinator_phone'),
  ('coordinator phone','coordinator_phone'),
  ('coordinator contact','coordinator_phone'),
  ('coordinator mobile','coordinator_phone'),
  ('coordinator phone number','coordinator_phone'),
  ('coordinator contact number','coordinator_phone'),
  ('coordinator mobile number','coordinator_phone'),
  ('teacher phone','coordinator_phone'),
  ('teacher contact','coordinator_phone'),
  ('coordinator address','coordinator_address'),
  ('teacher address','coordinator_address'),
  ('school kit drop date','kit_drop_date'),
  ('kit drop date','kit_drop_date'),
  ('kit date','kit_drop_date'),
  ('kit given date','kit_drop_date'),
  ('kit distribution date','kit_drop_date'),
  ('date of kit drop','kit_drop_date'),
  ('kit delivered on','kit_drop_date'),
  ('no of kits','number_of_kits'),
  ('number of kits','number_of_kits'),
  ('kits','number_of_kits'),
  ('kit count','number_of_kits'),
  ('kits given','number_of_kits'),
  ('no of kit','number_of_kits'),
  ('number of kit','number_of_kits'),
  ('channel','channel'),
  ('source channel','channel'),
  ('channel name','channel'),
  ('distribution channel','channel'),
  ('partner','partner'),
  ('partner name','partner'),
  ('channel partner','partner'),
  ('sales spoc','sales_spoc'),
  ('spoc','sales_spoc'),
  ('sales person','sales_spoc'),
  ('salesperson','sales_spoc'),
  ('sales spoc name','sales_spoc'),
  ('sales owner','sales_spoc'),
  ('registration date','registration_date'),
  ('date of registration','registration_date'),
  ('timestamp','registration_date'),
  ('submitted at','registration_date'),
  ('school registered','school_registered'),
  ('registered','school_registered'),
  ('registration status','school_registered'),
  ('is registered','school_registered'),
  ('total students','total_students'),
  ('total','total_students'),
  ('total student count','total_students'),
  ('total no of students','total_students'),
  ('total number of students','total_students')
ON CONFLICT (alias_norm) DO NOTHING;

-- Starter CITY -> DISTRICT lookup (editable in Settings). Used only when a sheet has no District column.
INSERT INTO geo_city_district (state, city, district) VALUES
  ('Maharashtra','Pune','Pune'),
  ('Maharashtra','Pimpri Chinchwad','Pune'),
  ('Maharashtra','Mumbai','Mumbai City'),
  ('Maharashtra','Navi Mumbai','Thane'),
  ('Maharashtra','Thane','Thane'),
  ('Maharashtra','Nagpur','Nagpur'),
  ('Maharashtra','Nashik','Nashik'),
  ('Maharashtra','Kolhapur','Kolhapur'),
  ('Maharashtra','Aurangabad','Chhatrapati Sambhajinagar'),
  ('Maharashtra','Chhatrapati Sambhajinagar','Chhatrapati Sambhajinagar'),
  ('Maharashtra','Solapur','Solapur'),
  ('Maharashtra','Sangli','Sangli'),
  ('Maharashtra','Satara','Satara'),
  ('Maharashtra','Baramati','Pune'),
  ('Maharashtra','Ichalkaranji','Kolhapur'),
  ('Maharashtra','Amravati','Amravati'),
  ('Maharashtra','Nanded','Nanded'),
  ('Gujarat','Ahmedabad','Ahmedabad'),
  ('Gujarat','Surat','Surat'),
  ('Gujarat','Vadodara','Vadodara'),
  ('Gujarat','Baroda','Vadodara'),
  ('Gujarat','Rajkot','Rajkot'),
  ('Gujarat','Gandhinagar','Gandhinagar'),
  ('Gujarat','Bhavnagar','Bhavnagar'),
  ('Gujarat','Anand','Anand'),
  ('Gujarat','Jamnagar','Jamnagar'),
  ('Gujarat','Vapi','Valsad'),
  ('Gujarat','Navsari','Navsari'),
  ('Gujarat','Mehsana','Mehsana'),
  ('Uttar Pradesh','Lucknow','Lucknow'),
  ('Uttar Pradesh','Kanpur','Kanpur Nagar'),
  ('Uttar Pradesh','Varanasi','Varanasi'),
  ('Uttar Pradesh','Noida','Gautam Buddha Nagar'),
  ('Uttar Pradesh','Greater Noida','Gautam Buddha Nagar'),
  ('Uttar Pradesh','Ghaziabad','Ghaziabad'),
  ('Uttar Pradesh','Agra','Agra'),
  ('Uttar Pradesh','Prayagraj','Prayagraj'),
  ('Uttar Pradesh','Allahabad','Prayagraj'),
  ('Uttar Pradesh','Meerut','Meerut'),
  ('Uttar Pradesh','Gorakhpur','Gorakhpur'),
  ('Uttar Pradesh','Bareilly','Bareilly'),
  ('Uttar Pradesh','Aligarh','Aligarh'),
  ('Karnataka','Bengaluru','Bengaluru Urban'),
  ('Karnataka','Bangalore','Bengaluru Urban'),
  ('Karnataka','Mysuru','Mysuru'),
  ('Karnataka','Mysore','Mysuru'),
  ('Karnataka','Hubballi','Dharwad'),
  ('Karnataka','Hubli','Dharwad'),
  ('Karnataka','Dharwad','Dharwad'),
  ('Karnataka','Mangaluru','Dakshina Kannada'),
  ('Karnataka','Mangalore','Dakshina Kannada'),
  ('Karnataka','Belagavi','Belagavi'),
  ('Karnataka','Belgaum','Belagavi'),
  ('Karnataka','Kalaburagi','Kalaburagi'),
  ('Delhi','New Delhi','New Delhi'),
  ('Rajasthan','Jaipur','Jaipur'),
  ('Rajasthan','Jodhpur','Jodhpur'),
  ('Rajasthan','Udaipur','Udaipur'),
  ('Rajasthan','Kota','Kota'),
  ('Madhya Pradesh','Indore','Indore'),
  ('Madhya Pradesh','Bhopal','Bhopal'),
  ('Madhya Pradesh','Gwalior','Gwalior'),
  ('Madhya Pradesh','Jabalpur','Jabalpur'),
  ('Telangana','Hyderabad','Hyderabad'),
  ('Telangana','Warangal','Hanamkonda'),
  ('Tamil Nadu','Chennai','Chennai'),
  ('Tamil Nadu','Coimbatore','Coimbatore'),
  ('Tamil Nadu','Madurai','Madurai'),
  ('West Bengal','Kolkata','Kolkata'),
  ('West Bengal','Howrah','Howrah'),
  ('Kerala','Kochi','Ernakulam'),
  ('Kerala','Thiruvananthapuram','Thiruvananthapuram'),
  ('Haryana','Gurugram','Gurugram'),
  ('Haryana','Gurgaon','Gurugram'),
  ('Haryana','Faridabad','Faridabad'),
  ('Punjab','Ludhiana','Ludhiana'),
  ('Punjab','Amritsar','Amritsar'),
  ('Bihar','Patna','Patna'),
  ('Odisha','Bhubaneswar','Khordha'),
  ('Odisha','Cuttack','Cuttack'),
  ('Goa','Panaji','North Goa'),
  ('Goa','Margao','South Goa')
ON CONFLICT DO NOTHING;
