-- More CITY -> DISTRICT rows across India. They also let the CRM fill in a missing State from the City
-- (only when the city name belongs to exactly one state).
INSERT INTO geo_city_district (state, city, district) VALUES
  ('Gujarat','Ahmedabad','Ahmedabad'),
  ('Gujarat','Surat','Surat'),
  ('Gujarat','Vadodara','Vadodara'),
  ('Gujarat','Baroda','Vadodara'),
  ('Gujarat','Rajkot','Rajkot'),
  ('Gujarat','Bhavnagar','Bhavnagar'),
  ('Gujarat','Jamnagar','Jamnagar'),
  ('Gujarat','Junagadh','Junagadh'),
  ('Gujarat','Gandhinagar','Gandhinagar'),
  ('Gujarat','Anand','Anand'),
  ('Gujarat','Nadiad','Kheda'),
  ('Gujarat','Mehsana','Mehsana'),
  ('Gujarat','Morbi','Morbi'),
  ('Gujarat','Bharuch','Bharuch'),
  ('Gujarat','Ankleshwar','Bharuch'),
  ('Gujarat','Navsari','Navsari'),
  ('Gujarat','Valsad','Valsad'),
  ('Gujarat','Vapi','Valsad'),
  ('Gujarat','Porbandar','Porbandar'),
  ('Gujarat','Gandhidham','Kutch'),
  ('Gujarat','Bhuj','Kutch'),
  ('Gujarat','Palanpur','Banaskantha'),
  ('Gujarat','Himatnagar','Sabarkantha'),
  ('Gujarat','Himmatnagar','Sabarkantha'),
  ('Gujarat','Himmtnagar','Sabarkantha'),
  ('Gujarat','Godhra','Panchmahal'),
  ('Gujarat','Dahod','Dahod'),
  ('Gujarat','Patan','Patan'),
  ('Gujarat','Amreli','Amreli'),
  ('Gujarat','Botad','Botad'),
  ('Gujarat','Surendranagar','Surendranagar'),
  ('Gujarat','Veraval','Gir Somnath'),
  ('Gujarat','Modasa','Aravalli'),
  ('Gujarat','Kalol','Gandhinagar'),
  ('Gujarat','Vyara','Tapi'),
  ('Gujarat','Bardoli','Surat'),
  ('Maharashtra','Nagpur','Nagpur'),
  ('Maharashtra','Nashik','Nashik'),
  ('Maharashtra','Kolhapur','Kolhapur'),
  ('Maharashtra','Solapur','Solapur'),
  ('Maharashtra','Sangli','Sangli'),
  ('Maharashtra','Satara','Satara'),
  ('Maharashtra','Ahmednagar','Ahmednagar'),
  ('Maharashtra','Jalgaon','Jalgaon'),
  ('Maharashtra','Dhule','Dhule'),
  ('Maharashtra','Amravati','Amravati'),
  ('Maharashtra','Akola','Akola'),
  ('Maharashtra','Latur','Latur'),
  ('Maharashtra','Nanded','Nanded'),
  ('Maharashtra','Chhatrapati Sambhajinagar','Chhatrapati Sambhajinagar'),
  ('Maharashtra','Kalyan','Thane'),
  ('Maharashtra','Dombivli','Thane'),
  ('Maharashtra','Bhiwandi','Thane'),
  ('Maharashtra','Vasai','Palghar'),
  ('Maharashtra','Virar','Palghar'),
  ('Maharashtra','Panvel','Raigad'),
  ('Maharashtra','Ratnagiri','Ratnagiri'),
  ('Maharashtra','Baramati','Pune'),
  ('Maharashtra','Chandrapur','Chandrapur'),
  ('Maharashtra','Wardha','Wardha'),
  ('Maharashtra','Yavatmal','Yavatmal'),
  ('Maharashtra','Ichalkaranji','Kolhapur'),
  ('Maharashtra','Malegaon','Nashik'),
  ('Maharashtra','Jalna','Jalna'),
  ('Maharashtra','Beed','Beed'),
  ('Maharashtra','Parbhani','Parbhani'),
  ('Maharashtra','Karad','Satara'),
  ('Maharashtra','Miraj','Sangli'),('Maharashtra','Islampur','Sangli'),('Maharashtra','Kagal','Kolhapur'),('Maharashtra','Gadhinglaj','Kolhapur'),
  ('Maharashtra','Jaysingpur','Kolhapur'),('Maharashtra','Ulhasnagar','Thane'),('Maharashtra','Ambernath','Thane'),('Maharashtra','Badlapur','Thane'),
  ('Maharashtra','Titwala','Thane'),('Maharashtra','Shahapur','Thane'),('Maharashtra','Murbad','Thane'),('Maharashtra','Talegaon','Pune'),
  ('Maharashtra','Chakan','Pune'),('Maharashtra','Lonavala','Pune'),('Maharashtra','Shirur','Pune'),
  ('Karnataka','Bengaluru','Bengaluru Urban'),
  ('Karnataka','Bangalore','Bengaluru Urban'),
  ('Karnataka','Mysuru','Mysuru'),
  ('Karnataka','Mysore','Mysuru'),
  ('Karnataka','Mangaluru','Dakshina Kannada'),
  ('Karnataka','Mangalore','Dakshina Kannada'),
  ('Karnataka','Hubballi','Dharwad'),
  ('Karnataka','Hubli','Dharwad'),
  ('Karnataka','Dharwad','Dharwad'),
  ('Karnataka','Belagavi','Belagavi'),
  ('Karnataka','Belgaum','Belagavi'),
  ('Karnataka','Kalaburagi','Kalaburagi'),
  ('Karnataka','Davanagere','Davanagere'),
  ('Karnataka','Ballari','Ballari'),
  ('Karnataka','Shivamogga','Shivamogga'),
  ('Karnataka','Tumakuru','Tumakuru'),
  ('Karnataka','Udupi','Udupi'),
  ('Tamil Nadu','Chennai','Chennai'),
  ('Tamil Nadu','Coimbatore','Coimbatore'),
  ('Tamil Nadu','Madurai','Madurai'),
  ('Tamil Nadu','Tiruchirappalli','Tiruchirappalli'),
  ('Tamil Nadu','Trichy','Tiruchirappalli'),
  ('Tamil Nadu','Salem','Salem'),
  ('Tamil Nadu','Tirunelveli','Tirunelveli'),
  ('Tamil Nadu','Erode','Erode'),
  ('Tamil Nadu','Vellore','Vellore'),
  ('Tamil Nadu','Tiruppur','Tiruppur'),
  ('Tamil Nadu','Thoothukudi','Thoothukudi'),
  ('Telangana','Hyderabad','Hyderabad'),
  ('Telangana','Secunderabad','Hyderabad'),
  ('Telangana','Warangal','Warangal'),
  ('Telangana','Karimnagar','Karimnagar'),
  ('Telangana','Nizamabad','Nizamabad'),
  ('Telangana','Khammam','Khammam'),
  ('Andhra Pradesh','Visakhapatnam','Visakhapatnam'),
  ('Andhra Pradesh','Vijayawada','NTR'),
  ('Andhra Pradesh','Guntur','Guntur'),
  ('Andhra Pradesh','Nellore','Nellore'),
  ('Andhra Pradesh','Tirupati','Tirupati'),
  ('Andhra Pradesh','Kurnool','Kurnool'),
  ('Andhra Pradesh','Kakinada','Kakinada'),
  ('Andhra Pradesh','Rajahmundry','East Godavari'),
  ('Kerala','Kozhikode','Kozhikode'),
  ('Kerala','Calicut','Kozhikode'),
  ('Kerala','Thrissur','Thrissur'),
  ('Kerala','Kollam','Kollam'),
  ('Kerala','Kannur','Kannur'),
  ('Kerala','Ernakulam','Ernakulam'),
  ('Kerala','Kottayam','Kottayam'),
  ('Kerala','Palakkad','Palakkad'),
  ('Kerala','Malappuram','Malappuram'),
  ('Delhi','Delhi','Delhi'),
  ('Delhi','New Delhi','New Delhi'),
  ('Uttar Pradesh','Lucknow','Lucknow'),
  ('Uttar Pradesh','Kanpur','Kanpur Nagar'),
  ('Uttar Pradesh','Agra','Agra'),
  ('Uttar Pradesh','Varanasi','Varanasi'),
  ('Uttar Pradesh','Prayagraj','Prayagraj'),
  ('Uttar Pradesh','Allahabad','Prayagraj'),
  ('Uttar Pradesh','Ghaziabad','Ghaziabad'),
  ('Uttar Pradesh','Noida','Gautam Buddh Nagar'),
  ('Uttar Pradesh','Greater Noida','Gautam Buddh Nagar'),
  ('Uttar Pradesh','Meerut','Meerut'),
  ('Uttar Pradesh','Bareilly','Bareilly'),
  ('Uttar Pradesh','Aligarh','Aligarh'),
  ('Uttar Pradesh','Moradabad','Moradabad'),
  ('Uttar Pradesh','Gorakhpur','Gorakhpur'),
  ('Uttar Pradesh','Jhansi','Jhansi'),
  ('Uttar Pradesh','Mathura','Mathura'),
  ('Uttar Pradesh','Ayodhya','Ayodhya'),
  ('Rajasthan','Jaipur','Jaipur'),
  ('Rajasthan','Jodhpur','Jodhpur'),
  ('Rajasthan','Udaipur','Udaipur'),
  ('Rajasthan','Kota','Kota'),
  ('Rajasthan','Ajmer','Ajmer'),
  ('Rajasthan','Bikaner','Bikaner'),
  ('Rajasthan','Bhilwara','Bhilwara'),
  ('Rajasthan','Alwar','Alwar'),
  ('Rajasthan','Sikar','Sikar'),
  ('Madhya Pradesh','Indore','Indore'),
  ('Madhya Pradesh','Bhopal','Bhopal'),
  ('Madhya Pradesh','Jabalpur','Jabalpur'),
  ('Madhya Pradesh','Gwalior','Gwalior'),
  ('Madhya Pradesh','Ujjain','Ujjain'),
  ('Madhya Pradesh','Sagar','Sagar'),
  ('Madhya Pradesh','Ratlam','Ratlam'),
  ('Madhya Pradesh','Rewa','Rewa'),
  ('West Bengal','Kolkata','Kolkata'),
  ('West Bengal','Siliguri','Darjeeling'),
  ('West Bengal','Durgapur','Paschim Bardhaman'),
  ('West Bengal','Asansol','Paschim Bardhaman'),
  ('West Bengal','Kharagpur','Paschim Medinipur'),
  ('Punjab','Jalandhar','Jalandhar'),
  ('Punjab','Patiala','Patiala'),
  ('Punjab','Bathinda','Bathinda'),
  ('Punjab','Mohali','Sahibzada Ajit Singh Nagar'),
  ('Chandigarh','Chandigarh','Chandigarh'),
  ('Haryana','Panipat','Panipat'),
  ('Haryana','Ambala','Ambala'),
  ('Haryana','Karnal','Karnal'),
  ('Haryana','Hisar','Hisar'),
  ('Haryana','Rohtak','Rohtak'),
  ('Haryana','Sonipat','Sonipat'),
  ('Haryana','Panchkula','Panchkula'),
  ('Odisha','Rourkela','Sundargarh'),
  ('Odisha','Sambalpur','Sambalpur'),
  ('Odisha','Berhampur','Ganjam'),
  ('Odisha','Puri','Puri'),
  ('Jharkhand','Ranchi','Ranchi'),
  ('Jharkhand','Jamshedpur','East Singhbhum'),
  ('Jharkhand','Dhanbad','Dhanbad'),
  ('Jharkhand','Bokaro','Bokaro'),
  ('Jharkhand','Hazaribagh','Hazaribagh'),
  ('Jharkhand','Deoghar','Deoghar'),
  ('Chhattisgarh','Raipur','Raipur'),
  ('Chhattisgarh','Bhilai','Durg'),
  ('Chhattisgarh','Durg','Durg'),
  ('Chhattisgarh','Bilaspur','Bilaspur'),
  ('Chhattisgarh','Korba','Korba'),
  ('Assam','Guwahati','Kamrup Metropolitan'),
  ('Assam','Dibrugarh','Dibrugarh'),
  ('Assam','Silchar','Cachar'),
  ('Assam','Jorhat','Jorhat'),
  ('Uttarakhand','Dehradun','Dehradun'),
  ('Uttarakhand','Haridwar','Haridwar'),
  ('Uttarakhand','Roorkee','Haridwar'),
  ('Uttarakhand','Haldwani','Nainital'),
  ('Uttarakhand','Rishikesh','Dehradun'),
  ('Himachal Pradesh','Shimla','Shimla'),
  ('Himachal Pradesh','Mandi','Mandi'),
  ('Himachal Pradesh','Dharamshala','Kangra'),
  ('Himachal Pradesh','Solan','Solan'),
  ('Jammu and Kashmir','Jammu','Jammu'),
  ('Jammu and Kashmir','Srinagar','Srinagar')
ON CONFLICT DO NOTHING;

-- Fill a missing state where the city names exactly one state, then a missing district.
UPDATE schools s SET state = g.state, updated_at = now()
  FROM (SELECT lower(city) AS city, min(state) AS state FROM geo_city_district GROUP BY lower(city) HAVING count(DISTINCT state) = 1) g
 WHERE (s.state IS NULL OR s.state = '') AND lower(s.city) = g.city;
UPDATE schools s SET district = g.district, district_origin = 'LOOKUP', updated_at = now()
  FROM geo_city_district g
 WHERE s.district IS NULL AND lower(s.state) = lower(g.state) AND lower(s.city) = lower(g.city);
